// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interface/interface.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Measure struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Measure_FValue
	//	*Measure_IValue
	Value                isMeasure_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Measure) Reset()         { *m = Measure{} }
func (m *Measure) String() string { return proto.CompactTextString(m) }
func (*Measure) ProtoMessage()    {}
func (*Measure) Descriptor() ([]byte, []int) {
	return fileDescriptor_460c38aebb3cb2d6, []int{0}
}

func (m *Measure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Measure.Unmarshal(m, b)
}
func (m *Measure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Measure.Marshal(b, m, deterministic)
}
func (m *Measure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Measure.Merge(m, src)
}
func (m *Measure) XXX_Size() int {
	return xxx_messageInfo_Measure.Size(m)
}
func (m *Measure) XXX_DiscardUnknown() {
	xxx_messageInfo_Measure.DiscardUnknown(m)
}

var xxx_messageInfo_Measure proto.InternalMessageInfo

func (m *Measure) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type isMeasure_Value interface {
	isMeasure_Value()
}

type Measure_FValue struct {
	FValue float32 `protobuf:"fixed32,2,opt,name=fValue,proto3,oneof"`
}

type Measure_IValue struct {
	IValue int32 `protobuf:"varint,3,opt,name=iValue,proto3,oneof"`
}

func (*Measure_FValue) isMeasure_Value() {}

func (*Measure_IValue) isMeasure_Value() {}

func (m *Measure) GetValue() isMeasure_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Measure) GetFValue() float32 {
	if x, ok := m.GetValue().(*Measure_FValue); ok {
		return x.FValue
	}
	return 0
}

func (m *Measure) GetIValue() int32 {
	if x, ok := m.GetValue().(*Measure_IValue); ok {
		return x.IValue
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Measure) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Measure_FValue)(nil),
		(*Measure_IValue)(nil),
	}
}

func init() {
	proto.RegisterType((*Measure)(nil), "sensocare.messages.Measure")
}

func init() {
	proto.RegisterFile("interface/interface.proto", fileDescriptor_460c38aebb3cb2d6)
}

var fileDescriptor_460c38aebb3cb2d6 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0xcc, 0xcc, 0x2b, 0x49,
	0x2d, 0x4a, 0x4b, 0x4c, 0x4e, 0xd5, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84,
	0x8a, 0x53, 0xf3, 0x8a, 0xf3, 0x93, 0x13, 0x8b, 0x52, 0xf5, 0x72, 0x53, 0x8b, 0x8b, 0x13, 0xd3,
	0x53, 0x8b, 0x95, 0x52, 0xb8, 0xd8, 0x7d, 0x53, 0x13, 0x8b, 0x4b, 0x8b, 0x52, 0x85, 0x64, 0xb8,
	0x38, 0x4b, 0x32, 0x81, 0x12, 0x25, 0x89, 0xb9, 0x05, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41,
	0x08, 0x01, 0x21, 0x09, 0x2e, 0xb6, 0xb4, 0xb0, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0xa0, 0x14,
	0x93, 0x07, 0x43, 0x10, 0x94, 0x0f, 0x92, 0xc9, 0x84, 0xc8, 0x30, 0x03, 0x65, 0x58, 0x41, 0x32,
	0x10, 0xbe, 0x13, 0x3b, 0x17, 0x6b, 0x19, 0x98, 0x21, 0x1e, 0x25, 0x5a, 0x90, 0x9d, 0xae, 0x0f,
	0xb3, 0xd5, 0x1a, 0xc6, 0x48, 0x62, 0x03, 0xbb, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5f,
	0xbf, 0xd7, 0x0d, 0xb6, 0x00, 0x00, 0x00,
}
